eclipse-packaging/packages

- .project
Filter so that the nested project folder is visible, but not the contents under that folder.  This helps avoid search finding multiple hits for what is effectively the same underlying resource.
> Filter nested projects from the root project

- packages/org.eclipse.epp.package.committers.product/epp.product
- packages/org.eclipse.epp.package.committers.product/p2.inf
- packages/org.eclipse.epp.package.modeling.product/epp.product
- packages/org.eclipse.epp.package.modeling.product/p2.inf
- packages/org.eclipse.epp.package.rcp.product/epp.product
Include this for the committers, modeling, and rcp products where I expect such spies will be significantly useful, but not for jee.
https://github.com/eclipse-pde/eclipse.pde/pull/479
> Include org.eclipse.pde.spies in products that include org.eclipse.pde

- releng/org.eclipse.epp.config/parent/pom.xml
- releng/org.eclipse.epp.config/tools/promote-a-build.sh
I had previously done part of this before moving to GitHub but I had not gone through the checklist, so I am now filling in the missing items.
See also https://git.eclipse.org/r/c/epp/org.eclipse.epp.packages/+/200572
Part of #5
> Prepare repo for 2023-06 M1

- packages/org.eclipse.epp.package.committers.product/epp.product
- packages/org.eclipse.epp.package.committers.product/p2.inf
- packages/org.eclipse.epp.package.cpp.product/epp.product
- packages/org.eclipse.epp.package.cpp.product/p2.inf
- packages/org.eclipse.epp.package.dsl.product/epp.product
- packages/org.eclipse.epp.package.dsl.product/p2.inf
- packages/org.eclipse.epp.package.embedcpp.product/epp.product
- packages/org.eclipse.epp.package.embedcpp.product/p2.inf
- packages/org.eclipse.epp.package.java.product/epp.product
- packages/org.eclipse.epp.package.java.product/p2.inf
- packages/org.eclipse.epp.package.jee.product/epp.product
- packages/org.eclipse.epp.package.jee.product/p2.inf
- packages/org.eclipse.epp.package.modeling.product/epp.product
- packages/org.eclipse.epp.package.modeling.product/p2.inf
- packages/org.eclipse.epp.package.parallel.product/epp.product
- packages/org.eclipse.epp.package.parallel.product/p2.inf
- packages/org.eclipse.epp.package.php.product/epp.product
- packages/org.eclipse.epp.package.php.product/p2.inf
- packages/org.eclipse.epp.package.rcp.product/epp.product
- packages/org.eclipse.epp.package.rcp.product/p2.inf
- packages/org.eclipse.epp.package.scout.product/epp.product
- packages/org.eclipse.epp.package.scout.product/p2.inf
Summary of how and why I have added MyLyn to EPPs.
Below is all the mylyn features in 2023-06 M3 (not including wikitext stuff)
Included in all EPPs:
- org.eclipse.mylyn.ide_feature
- org.eclipse.mylyn.git
- org.eclipse.mylyn.hudson
- org.eclipse.mylyn.reviews.feature
Indirectly included in all EPPs because of a dependency chain starting above:
- org.eclipse.mylyn_feature
- included as part of context_feature
- org.eclipse.mylyn.builds
- included as part of mylyn_feature
- org.eclipse.mylyn.commons
- included as part of mylyn_feature
- org.eclipse.mylyn.commons.identity
- included as part of mylyn_feature
- org.eclipse.mylyn.commons.notifications
- included as part of mylyn_feature
- org.eclipse.mylyn.commons.repositories
- included as part of mylyn_feature
- …
> Add Mylyn to EPP packages

- packages/org.eclipse.epp.package.committers.product/epp.product
- packages/org.eclipse.epp.package.cpp.product/epp.product
- packages/org.eclipse.epp.package.dsl.product/epp.product
- packages/org.eclipse.epp.package.embedcpp.product/epp.product
- packages/org.eclipse.epp.package.java.product/epp.product
- packages/org.eclipse.epp.package.jee.product/epp.product
- packages/org.eclipse.epp.package.modeling.product/epp.product
- packages/org.eclipse.epp.package.parallel.product/epp.product
- packages/org.eclipse.epp.package.php.product/epp.product
- packages/org.eclipse.epp.package.rcp.product/epp.product
- packages/org.eclipse.epp.package.scout.product/epp.product
Effectively this should not change the resulting product.
@jonahgraham btw. would it in general be interesting for EPP to use mixed products?
For each package I see a feature that only contains the branding plugin.
Would it be possible to include that branding plugin directly in the product or is it really required? The `epp.website.xml` of those features seems not to be included in the build binary artifacts, so it could actually be moved to the product or branding-plugin project.
Or would a change in this regard cause problems for updates?
> Adapt Product attributes to latest PDE Product-Editor enhancements

- packages/org.eclipse.epp.package.committers.product/epp.product
- packages/org.eclipse.epp.package.cpp.product/epp.product
- packages/org.eclipse.epp.package.dsl.product/epp.product
- packages/org.eclipse.epp.package.embedcpp.product/epp.product
- packages/org.eclipse.epp.package.java.product/epp.product
- packages/org.eclipse.epp.package.jee.product/epp.product
- packages/org.eclipse.epp.package.modeling.product/epp.product
- packages/org.eclipse.epp.package.parallel.product/epp.product
- packages/org.eclipse.epp.package.php.product/epp.product
- packages/org.eclipse.epp.package.rcp.product/epp.product
- packages/org.eclipse.epp.package.scout.product/epp.product
Fixes https://github.com/eclipse-packaging/packages/issues/27
For all products this means that the implementation of the OSGi Service Loader Mediator Specification supplied by Eclipse-Platform, namly the 'org.apache.aries.spifly.dynamic.bundle' bundle has to be auto-started at level two, like it is already done for the Eclipse SDK managed by Eclipse-Platform.
All products that contain the slf4j.simple logging back-end, need to auto-start slf4j.simple as well.
Additionally a VM-property is set to turn slf4j.simple off by default. A user can then configure it as desired by modifying/setting the corresponding system-properties in the eclipse.ini, as defined in the SimpleLogger doc:
https://www.slf4j.org/api/org/slf4j/simple/SimpleLogger.html
If a product uses the o.e.m2e.logback feature, and …
> Configure Plug-in Start Levels to enable slf4j-2 logging

- packages/org.eclipse.epp.package.committers.product/epp.product
- packages/org.eclipse.epp.package.php.product/epp.product
- packages/org.eclipse.epp.package.scout.product/epp.product
Because the slf4j.simple is not included "naturally" by any of the features already in php, committers or scout, include it explicitly here.
Includes revert "Don't add slf4j.simple to products that don't include slf4j already" This reverts commit a1969248c1f9b76ed4c6d71d59f7965bb3e42bf2.
Fixes https://github.com/eclipse-packaging/packages/issues/27
> Add slf4j configuration for php, committers and scout

- packages/org.eclipse.epp.package.committers.product/epp.product
- packages/org.eclipse.epp.package.cpp.product/epp.product
- packages/org.eclipse.epp.package.dsl.product/epp.product
- packages/org.eclipse.epp.package.embedcpp.product/epp.product
- packages/org.eclipse.epp.package.java.product/epp.product
- packages/org.eclipse.epp.package.jee.product/epp.product
- packages/org.eclipse.epp.package.modeling.product/epp.product
- packages/org.eclipse.epp.package.parallel.product/epp.product
- packages/org.eclipse.epp.package.php.product/epp.product
- packages/org.eclipse.epp.package.rcp.product/epp.product
- packages/org.eclipse.epp.package.scout.product/epp.product
Fixes #27 specifically a follow up for #47:
https://github.com/eclipse-packaging/packages/pull/47#issuecomment-1692816329
> Always include slf4j.simple or m2e.logback in each package

- packages/org.eclipse.epp.package.committers.product/epp.product
- packages/org.eclipse.epp.package.committers.product/p2.inf
- packages/org.eclipse.epp.package.cpp.product/epp.product
- packages/org.eclipse.epp.package.cpp.product/p2.inf
- packages/org.eclipse.epp.package.dsl.product/epp.product
- packages/org.eclipse.epp.package.dsl.product/p2.inf
- packages/org.eclipse.epp.package.embedcpp.product/epp.product
- packages/org.eclipse.epp.package.embedcpp.product/p2.inf
- packages/org.eclipse.epp.package.java.product/epp.product
- packages/org.eclipse.epp.package.java.product/p2.inf
- packages/org.eclipse.epp.package.jee.product/epp.product
- packages/org.eclipse.epp.package.jee.product/p2.inf
- packages/org.eclipse.epp.package.modeling.product/epp.product
- packages/org.eclipse.epp.package.modeling.product/p2.inf
- packages/org.eclipse.epp.package.parallel.product/epp.product
- packages/org.eclipse.epp.package.parallel.product/p2.inf
- packages/org.eclipse.epp.package.php.product/epp.product
- packages/org.eclipse.epp.package.php.product/p2.inf
- packages/org.eclipse.epp.package.rcp.product/epp.product
- packages/org.eclipse.epp.package.rcp.product/p2.inf
- packages/org.eclipse.epp.package.scout.product/epp.product
- packages/org.eclipse.epp.package.scout.product/p2.inf
And remove the unnecessary specification of the property `org.eclipse.equinox.p2.type.product=true`, which Tycho/P2 already set by default.
Similar to https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1459.
> Move more product configuration from p2.inf to product-file

- packages/org.eclipse.epp.package.common.feature/feature.xml
- packages/org.eclipse.epp.package.common.feature/p2.inf
Fixes https://github.com/eclipse-packaging/packages/issues/81
I tested this by verifying that the expected `-D` ended up in eclipse.ini, then I created a 4.31 (2024-03) version of EPP locally with this change removed, did a install updates and confirmed the -D was removed.
> Use Apache HTTP Client by default in EPP

- packages/org.eclipse.epp.package.common.feature/feature.xml
- packages/org.eclipse.epp.package.common.feature/p2.inf
This seems to have caused p2 to make an application solution that doesn't work.
See #81
This reverts commit 3083907133ce22fd7ccb2dcd1f4fbbf6901ecb61.
> Revert "Use Apache HTTP Client by default in EPP"

- RELEASING.md
- packages/org.eclipse.epp.package.committers.feature/epp.website.xml
- packages/org.eclipse.epp.package.committers.product/p2.inf
- packages/org.eclipse.epp.package.cpp.feature/epp.website.xml
- packages/org.eclipse.epp.package.cpp.product/p2.inf
- packages/org.eclipse.epp.package.dsl.feature/epp.website.xml
- packages/org.eclipse.epp.package.dsl.product/p2.inf
- packages/org.eclipse.epp.package.embedcpp.feature/epp.website.xml
- packages/org.eclipse.epp.package.embedcpp.product/p2.inf
- packages/org.eclipse.epp.package.java.feature/epp.website.xml
- packages/org.eclipse.epp.package.java.product/p2.inf
- packages/org.eclipse.epp.package.jee.feature/epp.website.xml
- packages/org.eclipse.epp.package.jee.product/p2.inf
- packages/org.eclipse.epp.package.modeling.feature/epp.website.xml
- packages/org.eclipse.epp.package.modeling.product/p2.inf
- packages/org.eclipse.epp.package.php.feature/epp.website.xml
- packages/org.eclipse.epp.package.php.product/p2.inf
- packages/org.eclipse.epp.package.rcp.feature/epp.website.xml
- packages/org.eclipse.epp.package.rcp.product/p2.inf
- packages/org.eclipse.epp.package.scout.feature/epp.website.xml
- packages/org.eclipse.epp.package.scout.product/p2.inf
- releng/org.eclipse.epp.config/build.xml
Fixes missing version string updates. See https://github.com/eclipse-packaging/packages/issues/104#issuecomment-1889061846 for more details.
> Prepare repo for 2023-03 M1 (fixup)

- packages/org.eclipse.epp.package.committers.feature/feature.xml
- packages/org.eclipse.epp.package.committers.product/epp.product
- packages/org.eclipse.epp.package.common.feature/feature.xml
- packages/org.eclipse.epp.package.cpp.feature/feature.xml
- packages/org.eclipse.epp.package.cpp.product/epp.product
- packages/org.eclipse.epp.package.dsl.feature/feature.xml
- packages/org.eclipse.epp.package.dsl.product/epp.product
- packages/org.eclipse.epp.package.embedcpp.feature/feature.xml
- packages/org.eclipse.epp.package.embedcpp.product/epp.product
- packages/org.eclipse.epp.package.java.feature/feature.xml
- packages/org.eclipse.epp.package.java.product/epp.product
- packages/org.eclipse.epp.package.jee.feature/feature.xml
- packages/org.eclipse.epp.package.jee.product/epp.product
- packages/org.eclipse.epp.package.modeling.feature/feature.xml
- packages/org.eclipse.epp.package.modeling.product/epp.product
- packages/org.eclipse.epp.package.php.feature/feature.xml
- packages/org.eclipse.epp.package.php.product/epp.product
- packages/org.eclipse.epp.package.rcp.feature/feature.xml
- packages/org.eclipse.epp.package.rcp.product/epp.product
- packages/org.eclipse.epp.package.scout.feature/feature.xml
- packages/org.eclipse.epp.package.scout.product/epp.product
- Change all feature includes in products to be installMode="root".
- Add a requires/import to the corresponding product feature for each such modified feature include.
- Remove all references to org.eclipse.equinox.p2.user.ui and org.eclipse.help because these are included by org.eclipse.platform anyway.
- Change any non-epp plug-in include in a feature to a requires/import import, i.e., in the jee feature.xml.
https://github.com/eclipse-packaging/packages/issues/133
> Allow all product requirements to be updated

- releng/org.eclipse.epp.config/oomph/EPP.setup
- Clone the .github repo and name/qualitfy it packaging.github.
- Provide tasks to create .project, .gitigore, .settings folder.
- Enhance targlet to import the .github project.
- Create a working set for the org.eclipse.epp.github project.
- Enable linking preference; importing fails without that enabled.
> Enhance EPP.setup to clone the .github repository

- README.md
Because of the lack of auto-activation of profiles when some are manually specified on the command line, the common profile needs to be explicit
> Update single package build command

- RELEASING.md
The splash instructions have links to the current gitlab issue
xref: https://github.com/eclipse-packaging/packages/issues/178#issuecomment-2152617513
> Remove out of date info from releasing.md

- packages/org.eclipse.epp.package.scout/plugin.xml
This will update the intro page to start the SmartImportGitWizard (which we use for our test-procedure) instead of the GitCloneWizard.
> Use SmartImportGitWizard on Eclipse Scout intro-page

- releng/org.eclipse.epp.config/oomph/EPP.setup
- This ensures the clone task runs first rather than failing because the folder is not empty.
> Restrict resource creation tasks in .github clone to exclude bootstrap

- packages/org.eclipse.epp.package.committers.product/epp.product
- packages/org.eclipse.epp.package.cpp.product/epp.product
- packages/org.eclipse.epp.package.dsl.product/epp.product
- packages/org.eclipse.epp.package.embedcpp.product/epp.product
- packages/org.eclipse.epp.package.java.product/epp.product
- packages/org.eclipse.epp.package.jee.product/epp.product
- packages/org.eclipse.epp.package.modeling.product/epp.product
- packages/org.eclipse.epp.package.php.product/epp.product
- packages/org.eclipse.epp.package.rcp.product/epp.product
- packages/org.eclipse.epp.package.scout.product/epp.product
With https://github.com/eclipse-platform/eclipse.platform.ui/issues/1901 the auto-registration of link handlers was removed to avoid breaking of code signatures.
In order to use the 'eclipse+command' and 'eclipse+mpc' URI schemes on macOS, they must instead be pre-registered during .app bundle build time before code signing.
> Register eclipse+command / eclipse+mpc links for macOS packages

- releng/org.eclipse.epp.config/aggregation/packaging.aggr
- releng/org.eclipse.epp.config/parent/pom.xml
- releng/org.eclipse.epp.config/tools/upload-to-building.sh
- Use the JustJ milestone JRE repo for Java 21 which has the required riscv64 JREs.
- Include linux-gtk-riscv64 in the target-platform-configuration.
- Add a linux-gtk-riscv64 configuration to the packaging.aggr.
- Improve upload-to-building.sh to produce a nice name for the new package.
https://github.com/eclipse-packaging/packages/issues/213
> Produce packages for linux riscv64

- packages/org.eclipse.epp.package.committers.product/epp.product
- packages/org.eclipse.epp.package.cpp.product/epp.product
- packages/org.eclipse.epp.package.dsl.product/epp.product
- packages/org.eclipse.epp.package.embedcpp.product/epp.product
- packages/org.eclipse.epp.package.java.product/epp.product
- packages/org.eclipse.epp.package.jee.product/epp.product
- packages/org.eclipse.epp.package.modeling.product/epp.product
- packages/org.eclipse.epp.package.php.product/epp.product
- packages/org.eclipse.epp.package.rcp.product/epp.product
- packages/org.eclipse.epp.package.scout.product/epp.product
- -Djavax.net.ssl.trustStoreType=Windows-ROOT
- -Djavax.net.ssl.trustStore=NONE
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/929
> Specify VM options on Windows to use the system certificate store.

- .github/workflows/build.yml
Currently there are warnings in each element of the GH workflow matrix like:
`Warning:  The requested profile "epp.package.committers" could not be activated because it does not exist.`
and all packages are built in each build, which just takes much longer.
Part of https://github.com/eclipse-packaging/packages/issues/120
> [Build] Adapt Github workflows to parallel build and build with Maven 3.9.9

- releng/org.eclipse.epp.config/parent/pom.xml
This PR includes two changes
1. Update to Tycho 4.0.10
2. Don't set `LIBARCHIVE.creationtime` attribute in `tar.gz` archives
The former change is required by the latter. The latter permanently
fixes https://github.com/eclipse-packaging/packages/issues/53
This is similar to https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2530. See also https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2529.
And this probably also allows to remove the current workaround for https://github.com/eclipse-packaging/packages/issues/53.
> Don't set LIBARCHIVE.creationtime attribute in tar.gz archives and update to Tycho 4.0.10

- releng/org.eclipse.epp.config/parent/pom.xml
EPP currently builds all projects for seven different OS-arch combinations and all are build one after the other
Using the [`tycho-p2-director:materialize-products#parallel`](https://tycho.eclipseprojects.io/doc/4.0.10/tycho-p2-director-plugin/materialize-products-mojo.html#parallel) property the materialization for all configurations of one product can run in parallel which can speed up the build significantly.
After signing, the materialization is probably the longest running sub-task.
> [Build] Materialize products in parallel

- releng/org.eclipse.epp.config/parent/pom.xml
- releng/org.eclipse.epp.config/tools/promote-a-build.sh
- releng/org.eclipse.epp.config/tools/upload-to-staging.sh
Most of the work was already completed in commit c4446d0eac696691d555e0ed01c5a01a22bbb6af - this change does the last couple of steps up until "Wait for announcement that the staging repo is ready"
Part of #242
> prepare repo for run up to 2024-12 RC2/R

- packages/org.eclipse.epp.package.common/splash/INSTRUCTIONS.md
This is to increase visibility of usage errors when doing the manual image conversion. See https://github.com/eclipse-packaging/packages/issues/258
> Change the splash instruction to be a bulleted list

- RELEASING.md
- packages/org.eclipse.epp.package.modeling/about.properties
- packages/org.eclipse.epp.package.modeling/plugin.xml
I have not been doing the check incubation step for a while because everything contains incubating components. This doesn't seem likely to change anytime soon, so I have updated RELEASING.md to reflect current state.
However, during a cross check I found that modeling did include the required incubating components warning in the feature.properties but was missing it in the product aboutText blurb. This commit remedies that too.
> Update check incubation step

- packages/org.eclipse.epp.package.common/src/org/eclipse/epp/common/ContributeHandler.java
Contribute should be now on https://github.com/eclipse-ide
> Fix #284 : change contribute URL

- releng/org.eclipse.epp.config/parent/pom.xml
This reverts commit 2aec308ad3fa5d59d19cc09659ef12a96374f23f.
This change needed to wait until after 2025-03 was complete, or be applied if a respin was needed. The change probably should have been left as a draft.
> Revert "Back to staging repo"

- packages/org.eclipse.epp.package.common.feature/p2.inf
- Use a p2.inf in the common feautre to create an optional greedy dependency on org.eclipse.pde.runtime.
https://github.com/eclipse-packaging/packages/issues/294
> Support Plug-in Spies in All Packages

- packages/org.eclipse.epp.package.committers.product/epp.product
- packages/org.eclipse.epp.package.committers.product/pom.xml
- packages/org.eclipse.epp.package.dsl.product/pom.xml
- packages/org.eclipse.epp.package.modeling.product/epp.product
- packages/org.eclipse.epp.package.modeling.product/pom.xml
- packages/org.eclipse.epp.package.rcp.feature/feature.xml
- packages/org.eclipse.epp.package.rcp.product/epp.product
- packages/org.eclipse.epp.package.rcp.product/pom.xml
- packages/org.eclipse.epp.package.scout.product/epp.product
- releng/org.eclipse.epp.config/parent/pom.xml
- Add a new property install-sources which default to false.
- Use it to configure the installSources property of tycho-p2-director-plugin:materialize-products.
- Override the property in the products that SDK like.
- Remove the source feature from products and feature, replacing with the non-source feature where it's not redundant.
> Eliminate uses of the Platform source features

- packages/org.eclipse.epp.package.common.feature/feature.xml
- It's already the case that org.eclipse.epp.package.common.feature imports org.eclipse.equinox.p2.user.ui which includes org.eclipse.equinox.p2.user.ui which imports the
org.eclipse.ecf.provider.filetransfer.httpclient5 and org.eclipse.ecf.provider.filetransfer.httpclient5.win32 bundles, so I see no need for importing
org.eclipse.ecf.filetransfer.httpclient5.feature.
> Remove o.e.ecf.filetransfer.httpclient5.feature from common.feature

- packages/org.eclipse.epp.package.committers/plugin.xml
- packages/org.eclipse.epp.package.cpp/plugin.xml
- packages/org.eclipse.epp.package.dsl/plugin.xml
- packages/org.eclipse.epp.package.embedcpp/plugin.xml
- packages/org.eclipse.epp.package.java/plugin.xml
- packages/org.eclipse.epp.package.jee/plugin.xml
- packages/org.eclipse.epp.package.modeling/plugin.xml
- packages/org.eclipse.epp.package.php/plugin.xml
- packages/org.eclipse.epp.package.rcp/plugin.xml
- packages/org.eclipse.epp.package.scout/plugin.xml
- The warning `An entry for org.eclipse.platform/LegacyIDE.e4xmi is required in bin.includes` can be avoided by using
`platform:/plugin/org.eclipse.platform/LegacyIDE.e4xmi` instead.
> Eliminate warnings about org.eclipse.platform/LegacyIDE.e4xmi

- packages/org.eclipse.epp.package.committers.feature/p2.inf
- packages/org.eclipse.epp.package.committers.product/epp.p2.inf
- packages/org.eclipse.epp.package.common.feature/p2.inf
- packages/org.eclipse.epp.package.cpp.feature/p2.inf
- packages/org.eclipse.epp.package.cpp.product/epp.p2.inf
- packages/org.eclipse.epp.package.dsl.feature/p2.inf
- packages/org.eclipse.epp.package.dsl.product/epp.p2.inf
- packages/org.eclipse.epp.package.java.feature/p2.inf
- packages/org.eclipse.epp.package.java.product/epp.p2.inf
- packages/org.eclipse.epp.package.jee.feature/p2.inf
- packages/org.eclipse.epp.package.jee.product/epp.p2.inf
- packages/org.eclipse.epp.package.modeling.feature/p2.inf
- packages/org.eclipse.epp.package.modeling.product/epp.p2.inf
- packages/org.eclipse.epp.package.php.feature/p2.inf
- packages/org.eclipse.epp.package.php.product/epp.p2.inf
- packages/org.eclipse.epp.package.rcp.feature/p2.inf
- packages/org.eclipse.epp.package.rcp.product/epp.p2.inf
- packages/org.eclipse.epp.package.scout.feature/p2.inf
- packages/org.eclipse.epp.package.scout.product/epp.p2.inf
- Provide an empty source feature IU in org.eclipse.epp.package.common.feature for each source feature removed from the platform that was previously installed as a root in a product.
- Add an optional requirement to each product corresponding to a removed source feature.
- Remove all special update descriptors that are present only to prevent update from neon which is 9 years ago.
https://github.com/eclipse-packaging/packages/issues/333
> Ensure that all products can be updated from 2025-06 to 2025-09

- RELEASING.md
- Leave the existing documentation is place to be removed at a later time.
> Simplify the RELEASING.md instructions for the newly automated steps

- releng/org.eclipse.epp.config/org.eclipse.epp.releng.updater/src/org/eclipse/epp/releng/updater/Updater.java
- releng/org.eclipse.epp.config/tools/promote-a-build.sh
- releng/org.eclipse.epp.config/tools/upload-to-staging.sh
- It should include a proper `<past></past>` that can be computed and added automatically at the start of each cycle.
- Also update upload-to-staging.sh with the most recent +1s.
https://github.com/eclipse-packaging/packages/issues/353
> Automate updating promote-a-build.sh

- releng/org.eclipse.epp.config/aggregation/packaging.aggr
The following property should be mirrored:
- https://github.com/eclipse-packaging/packages/blob/1517bd3ec6dc38f4c0eb03a1714114e701d8510d/releng/org.eclipse.epp.config/parent/pom.xml#L241
> Ensure that the p2.statsURI properties is propagate to the aggregate
