eclipse-packaging/packages

- RELEASING.md
> Migrate releasing steps from hackmd to GitHub issue

- NOTICE
- RELEASING.md
> Update git repo URLs to GitHub

- packages/org.eclipse.epp.package.rcp.product/p2.inf
> Synchronize p2.inf for RCP to product file

- releng/org.eclipse.epp.config/tools/upload-to-staging.sh
> Last recorded +1s for 2023-03 release cycle

- releng/org.eclipse.epp.config/parent/pom.xml
> Back to simrel staging repo

- packages/org.eclipse.epp.package.committers.feature/epp.website.xml
- packages/org.eclipse.epp.package.cpp.feature/epp.website.xml
- packages/org.eclipse.epp.package.dsl.feature/epp.website.xml
- packages/org.eclipse.epp.package.embedcpp.feature/epp.website.xml
- packages/org.eclipse.epp.package.java.feature/epp.website.xml
- packages/org.eclipse.epp.package.jee.feature/epp.website.xml
- packages/org.eclipse.epp.package.modeling.feature/epp.website.xml
- packages/org.eclipse.epp.package.parallel.feature/epp.website.xml
- packages/org.eclipse.epp.package.php.feature/epp.website.xml
- packages/org.eclipse.epp.package.rcp.feature/epp.website.xml
- packages/org.eclipse.epp.package.scout.feature/epp.website.xml
- releng/org.eclipse.epp.config/parent/pom.xml
> Prepare repo for 2023-06 M3

- packages/org.eclipse.epp.package.committers.product/epp.product
- packages/org.eclipse.epp.package.committers.product/p2.inf
- packages/org.eclipse.epp.package.cpp.product/epp.product
- packages/org.eclipse.epp.package.cpp.product/p2.inf
- packages/org.eclipse.epp.package.dsl.product/epp.product
- packages/org.eclipse.epp.package.dsl.product/p2.inf
- packages/org.eclipse.epp.package.embedcpp.product/epp.product
- packages/org.eclipse.epp.package.embedcpp.product/p2.inf
- packages/org.eclipse.epp.package.java.product/epp.product
- packages/org.eclipse.epp.package.java.product/p2.inf
- packages/org.eclipse.epp.package.jee.product/epp.product
- packages/org.eclipse.epp.package.jee.product/p2.inf
- packages/org.eclipse.epp.package.modeling.product/epp.product
- packages/org.eclipse.epp.package.modeling.product/p2.inf
- packages/org.eclipse.epp.package.parallel.product/epp.product
- packages/org.eclipse.epp.package.parallel.product/p2.inf
- packages/org.eclipse.epp.package.php.product/epp.product
- packages/org.eclipse.epp.package.php.product/p2.inf
- packages/org.eclipse.epp.package.rcp.product/epp.product
- packages/org.eclipse.epp.package.rcp.product/p2.inf
- packages/org.eclipse.epp.package.scout.product/epp.product
- packages/org.eclipse.epp.package.scout.product/p2.inf
(Follow up to https://github.com/eclipse-packaging/packages/pull/24 to add
additional features that were missing in SimRel 2023-06 M3)
Summary of how and why I have added MyLyn to EPPs.
Below is all the mylyn features in 2023-06 RC1 (not including wikitext stuff)
Included in all EPPs:
- org.eclipse.mylyn.commons.activity
- org.eclipse.mylyn.egit.feature
- org.eclipse.mylyn.ide_feature
- org.eclipse.mylyn.git
- org.eclipse.mylyn.github.feature
- org.eclipse.mylyn.hudson
- org.eclipse.mylyn.reviews.feature
Indirectly included in all EPPs because of a dependency chain starting above:
- org.eclipse.mylyn_feature
- included as part of context_feature
- org.eclipse.mylyn.builds
- included as part of mylyn_feature
- org.eclipse.mylyn.commons
- included as part of mylyn_feature
- …
> Add Mylyn to EPP packages

- packages/org.eclipse.epp.package.committers.product/epp.product
- packages/org.eclipse.epp.package.cpp.product/epp.product
- packages/org.eclipse.epp.package.dsl.product/epp.product
- packages/org.eclipse.epp.package.dsl.product/p2.inf
- packages/org.eclipse.epp.package.embedcpp.product/epp.product
- packages/org.eclipse.epp.package.java.product/epp.product
- packages/org.eclipse.epp.package.jee.product/epp.product
- packages/org.eclipse.epp.package.modeling.product/epp.product
- packages/org.eclipse.epp.package.parallel.product/epp.product
- packages/org.eclipse.epp.package.php.product/epp.product
- packages/org.eclipse.epp.package.rcp.product/epp.product
- packages/org.eclipse.epp.package.scout.product/epp.product
Follow up to #19, #24, #26
Fixes #30
> Remove Mylyn from DSL package

- releng/org.eclipse.epp.config/oomph/EPP.setup
- releng/org.eclipse.epp.config/parent/pom.xml
Without these extra repositories the Targlet of the Oomph setup fails in a clean workspace.
@merks or am I doing something wrong?
> Add required justj repositories to EPP Packages Oomph setup

- CHANGELOG.md
> Add details about logging support

- releng/org.eclipse.epp.config/parent/pom.xml
> Add orbit-approved-artifacts to available repos

- pom.xml
Fixup for d3ebeba0d04848fe9b0f25cc5dc03483d66df149
Fixes https://github.com/eclipse-packaging/packages/issues/85
> Remove references to parallel package

- CHANGELOG.md
See https://github.com/eclipse-packaging/packages/issues/81
> Add entry for ECF P2 backend change

- packages/org.eclipse.epp.package.committers.feature/epp.website.xml
This won't be visible until RC2 as the RC1 info has already been built.
> Update egit bug reporting location

- releng/org.eclipse.epp.config/parent/pom.xml
- releng/org.eclipse.epp.config/parent/product/pom.xml
- releng/org.eclipse.epp.config/tools/upload-to-staging.sh
see https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4336#note_1799582
> Temporarily don't build some parts of EPP to reduce disk usage

- releng/org.eclipse.epp.config/parent/pom.xml
- releng/org.eclipse.epp.config/parent/product/pom.xml
- releng/org.eclipse.epp.config/tools/upload-to-staging.sh
This reverts commit 657f6e6bed7d9577c62fb45a140d0a758f83bb3a.
> Revert "Temporarily don't build some parts of EPP to reduce disk usage"

- Jenkinsfile
- packages/org.eclipse.epp.package.committers.feature/epp.website.xml
- packages/org.eclipse.epp.package.cpp.feature/epp.website.xml
- packages/org.eclipse.epp.package.dsl.feature/epp.website.xml
- packages/org.eclipse.epp.package.embedcpp.feature/epp.website.xml
- packages/org.eclipse.epp.package.java.feature/epp.website.xml
- packages/org.eclipse.epp.package.jee.feature/epp.website.xml
- packages/org.eclipse.epp.package.modeling.feature/epp.website.xml
- packages/org.eclipse.epp.package.php.feature/epp.website.xml
- packages/org.eclipse.epp.package.rcp.feature/epp.website.xml
- packages/org.eclipse.epp.package.scout.feature/epp.website.xml
- releng/org.eclipse.epp.config/parent/pom.xml
Part of https://github.com/eclipse-packaging/packages/issues/123
> Prepare repo for 2024-03 RC1

- Jenkinsfile
https://github.com/eclipse-packaging/packages/issues/130
> Properly update Jenkinsfile to use Temurin Java 21.

- packages/org.eclipse.epp.package.modeling.product/epp.product
https://github.com/eclipse-simrel/simrel.build/pull/315
> Remove dependency on org.eclipse.emf.ecp.emfforms.sdk.feature

- Jenkinsfile
The provides a workaround for the lack of triggering from SimRel -> EPP, see https://github.com/eclipse-packaging/packages/issues/122
> Add triggers and email notifications to the build

- releng/org.eclipse.epp.config/tools/promote-a-build.sh
Fixes https://github.com/eclipse-packaging/packages/issues/142
> Ensure that there always exists a staging repository

- Jenkinsfile
- RELEASING.md
Fixes https://github.com/eclipse-packaging/packages/issues/122
> Trigger EPP build when SimRel content is updated

- packages/org.eclipse.epp.package.committers.feature/epp.website.xml
- packages/org.eclipse.epp.package.cpp.feature/epp.website.xml
- packages/org.eclipse.epp.package.dsl.feature/epp.website.xml
- packages/org.eclipse.epp.package.embedcpp.feature/epp.website.xml
- packages/org.eclipse.epp.package.java.feature/epp.website.xml
- packages/org.eclipse.epp.package.jee.feature/epp.website.xml
- packages/org.eclipse.epp.package.modeling.feature/epp.website.xml
- packages/org.eclipse.epp.package.php.feature/epp.website.xml
- packages/org.eclipse.epp.package.rcp.feature/epp.website.xml
- packages/org.eclipse.epp.package.scout.feature/epp.website.xml
- releng/org.eclipse.epp.config/parent/pom.xml
> Prepare repo for 2024-06 RC1

- releng/org.eclipse.epp.config/parent/pom.xml
> Back to simrel staging repo as we prepare for next build

- packages/org.eclipse.epp.package.committers.feature/epp.website.xml
- packages/org.eclipse.epp.package.cpp.feature/epp.website.xml
- packages/org.eclipse.epp.package.dsl.feature/epp.website.xml
- packages/org.eclipse.epp.package.embedcpp.feature/epp.website.xml
- packages/org.eclipse.epp.package.java.feature/epp.website.xml
- packages/org.eclipse.epp.package.jee.feature/epp.website.xml
- packages/org.eclipse.epp.package.modeling.feature/epp.website.xml
- packages/org.eclipse.epp.package.php.feature/epp.website.xml
- packages/org.eclipse.epp.package.rcp.feature/epp.website.xml
- packages/org.eclipse.epp.package.scout.feature/epp.website.xml
- releng/org.eclipse.epp.config/parent/pom.xml
- releng/org.eclipse.epp.config/tools/promote-a-build.sh
- releng/org.eclipse.epp.config/tools/upload-to-staging.sh
> Prepare repo for 2024-06 RC2

- packages/org.eclipse.epp.package.committers.feature/epp.website.xml
- packages/org.eclipse.epp.package.cpp.feature/epp.website.xml
- packages/org.eclipse.epp.package.dsl.feature/epp.website.xml
- packages/org.eclipse.epp.package.embedcpp.feature/epp.website.xml
- packages/org.eclipse.epp.package.java.feature/epp.website.xml
- packages/org.eclipse.epp.package.jee.feature/epp.website.xml
- packages/org.eclipse.epp.package.modeling.feature/epp.website.xml
- packages/org.eclipse.epp.package.php.feature/epp.website.xml
- packages/org.eclipse.epp.package.rcp.feature/epp.website.xml
- packages/org.eclipse.epp.package.scout.feature/epp.website.xml
- releng/org.eclipse.epp.config/parent/pom.xml
> prepare repo for 2024-09 M2

- packages/org.eclipse.epp.package.php.feature/epp.website.xml
Follow on from #186 for PHP package that had the same old link
> Update instructions for reporting WTP bugs

- packages/org.eclipse.epp.package.committers.feature/epp.website.xml
- packages/org.eclipse.epp.package.cpp.feature/epp.website.xml
- packages/org.eclipse.epp.package.dsl.feature/epp.website.xml
- packages/org.eclipse.epp.package.embedcpp.feature/epp.website.xml
- packages/org.eclipse.epp.package.java.feature/epp.website.xml
- packages/org.eclipse.epp.package.jee.feature/epp.website.xml
- packages/org.eclipse.epp.package.modeling.feature/epp.website.xml
- packages/org.eclipse.epp.package.php.feature/epp.website.xml
- packages/org.eclipse.epp.package.rcp.feature/epp.website.xml
- packages/org.eclipse.epp.package.scout.feature/epp.website.xml
- releng/org.eclipse.epp.config/parent/pom.xml
> prepare repo for 2024-09 M3

- packages/org.eclipse.epp.package.committers.feature/epp.website.xml
- packages/org.eclipse.epp.package.cpp.feature/epp.website.xml
- packages/org.eclipse.epp.package.dsl.feature/epp.website.xml
- packages/org.eclipse.epp.package.embedcpp.feature/epp.website.xml
- packages/org.eclipse.epp.package.java.feature/epp.website.xml
- packages/org.eclipse.epp.package.jee.feature/epp.website.xml
- packages/org.eclipse.epp.package.modeling.feature/epp.website.xml
- packages/org.eclipse.epp.package.php.feature/epp.website.xml
- packages/org.eclipse.epp.package.rcp.feature/epp.website.xml
- packages/org.eclipse.epp.package.scout.feature/epp.website.xml
- releng/org.eclipse.epp.config/parent/pom.xml
> prepare repo for 2024-09 RC1

- packages/org.eclipse.epp.package.committers.feature/epp.website.xml
- packages/org.eclipse.epp.package.cpp.feature/epp.website.xml
- packages/org.eclipse.epp.package.dsl.feature/epp.website.xml
- packages/org.eclipse.epp.package.embedcpp.feature/epp.website.xml
- packages/org.eclipse.epp.package.java.feature/epp.website.xml
- packages/org.eclipse.epp.package.jee.feature/epp.website.xml
- packages/org.eclipse.epp.package.modeling.feature/epp.website.xml
- packages/org.eclipse.epp.package.php.feature/epp.website.xml
- packages/org.eclipse.epp.package.rcp.feature/epp.website.xml
- packages/org.eclipse.epp.package.scout.feature/epp.website.xml
- releng/org.eclipse.epp.config/parent/pom.xml
- releng/org.eclipse.epp.config/tools/promote-a-build.sh
- releng/org.eclipse.epp.config/tools/upload-to-staging.sh
> prepare repo for 2024-09 RC2

- packages/org.eclipse.epp.package.committers.feature/epp.website.xml
- packages/org.eclipse.epp.package.cpp.feature/epp.website.xml
- packages/org.eclipse.epp.package.dsl.feature/epp.website.xml
- packages/org.eclipse.epp.package.embedcpp.feature/epp.website.xml
- packages/org.eclipse.epp.package.java.feature/epp.website.xml
- packages/org.eclipse.epp.package.jee.feature/epp.website.xml
- packages/org.eclipse.epp.package.modeling.feature/epp.website.xml
- packages/org.eclipse.epp.package.php.feature/epp.website.xml
- packages/org.eclipse.epp.package.rcp.feature/epp.website.xml
- packages/org.eclipse.epp.package.scout.feature/epp.website.xml
- releng/org.eclipse.epp.config/parent/pom.xml
> Prepare reoo for 2024-12 M2

- CHANGELOG.md
- packages/org.eclipse.epp.package.committers.product/epp.product
- packages/org.eclipse.epp.package.cpp.product/epp.product
- packages/org.eclipse.epp.package.dsl.product/epp.product
- packages/org.eclipse.epp.package.embedcpp.product/epp.product
- packages/org.eclipse.epp.package.java.product/epp.product
- packages/org.eclipse.epp.package.jee.product/epp.product
- packages/org.eclipse.epp.package.modeling.product/epp.product
- packages/org.eclipse.epp.package.php.product/epp.product
- packages/org.eclipse.epp.package.rcp.product/epp.product
- packages/org.eclipse.epp.package.scout.product/epp.product
> Add TM4E to all EPPs

- releng/org.eclipse.epp.config/tools/upload-to-staging.sh
> Update Last Recorded +1 for 2024-12 M1

- packages/org.eclipse.epp.package.committers.feature/epp.website.xml
- packages/org.eclipse.epp.package.cpp.feature/epp.website.xml
- packages/org.eclipse.epp.package.dsl.feature/epp.website.xml
- packages/org.eclipse.epp.package.embedcpp.feature/epp.website.xml
- packages/org.eclipse.epp.package.java.feature/epp.website.xml
- packages/org.eclipse.epp.package.jee.feature/epp.website.xml
- packages/org.eclipse.epp.package.modeling.feature/epp.website.xml
- packages/org.eclipse.epp.package.php.feature/epp.website.xml
- packages/org.eclipse.epp.package.rcp.feature/epp.website.xml
- packages/org.eclipse.epp.package.scout.feature/epp.website.xml
- releng/org.eclipse.epp.config/parent/pom.xml
> Prepare repo for 2024-12 M3

- releng/org.eclipse.epp.config/parent/pom.xml
- Update to Tycho 4.0.10
- Prepare for RC1
> Back to staging 2024-12

- packages/org.eclipse.epp.package.committers.feature/epp.website.xml
- packages/org.eclipse.epp.package.cpp.feature/epp.website.xml
- packages/org.eclipse.epp.package.dsl.feature/epp.website.xml
- packages/org.eclipse.epp.package.dsl.product/epp.product
- packages/org.eclipse.epp.package.embedcpp.feature/epp.website.xml
- packages/org.eclipse.epp.package.java.feature/epp.website.xml
- packages/org.eclipse.epp.package.jee.feature/epp.website.xml
- packages/org.eclipse.epp.package.modeling.feature/epp.website.xml
- packages/org.eclipse.epp.package.php.feature/epp.website.xml
- packages/org.eclipse.epp.package.rcp.feature/epp.website.xml
- packages/org.eclipse.epp.package.scout.feature/epp.website.xml
- Update/cleanup NewAndNoteworthy
> prepare repo for 2024-12 RC1

- CHANGELOG.md
> Add missing N&N about platform support and root certs on Windows

- releng/org.eclipse.epp.config/parent/pom.xml
> Back to 2024-12 staging repo

- releng/org.eclipse.epp.config/parent/product/pom.xml
As requested by EF here:
- https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5417#note_2937220
> Test pre-release signer service

- packages/org.eclipse.epp.package.committers.product/epp.product
- packages/org.eclipse.epp.package.cpp.product/epp.product
- packages/org.eclipse.epp.package.dsl.product/epp.product
- packages/org.eclipse.epp.package.embedcpp.product/epp.product
- packages/org.eclipse.epp.package.java.product/epp.product
- packages/org.eclipse.epp.package.jee.product/epp.product
- packages/org.eclipse.epp.package.modeling.product/epp.product
- packages/org.eclipse.epp.package.php.product/epp.product
- packages/org.eclipse.epp.package.rcp.product/epp.product
- packages/org.eclipse.epp.package.scout.product/epp.product
https://github.com/eclipse-packaging/packages/issues/251
> Remove -Djava.security.manager=allow from all products

- CHANGELOG.md
> Add N&N entry for removing Xmx/Xms

- packages/org.eclipse.epp.package.committers.feature/epp.website.xml
- packages/org.eclipse.epp.package.cpp.feature/epp.website.xml
- packages/org.eclipse.epp.package.dsl.feature/epp.website.xml
- packages/org.eclipse.epp.package.embedcpp.feature/epp.website.xml
- packages/org.eclipse.epp.package.java.feature/epp.website.xml
- packages/org.eclipse.epp.package.jee.feature/epp.website.xml
- packages/org.eclipse.epp.package.modeling.feature/epp.website.xml
- packages/org.eclipse.epp.package.php.feature/epp.website.xml
- packages/org.eclipse.epp.package.rcp.feature/epp.website.xml
- packages/org.eclipse.epp.package.scout.feature/epp.website.xml
- The testPlan URL http://www.eclipse.org/epp/testplan.php no longer exists.
> Use https for image links and clear the testPlan attribute

- releng/org.eclipse.epp.config/parent/pom.xml
Part of https://github.com/eclipse-packaging/packages/issues/282
> Back to staging repo

- releng/org.eclipse.epp.config/parent/pom.xml
This change was missed when I did PR #289
> Update RELEASE_MILESTONE for 2025-03 M1

- RELEASING.md
- releng/org.eclipse.epp.config/parent/pom.xml
- releng/org.eclipse.epp.config/tools/upload-to-staging.sh
> Back to staging repo for 2025-06

- packages/org.eclipse.epp.package.committers.feature/epp.website.xml
- packages/org.eclipse.epp.package.cpp.feature/epp.website.xml
- packages/org.eclipse.epp.package.dsl.feature/epp.website.xml
- packages/org.eclipse.epp.package.embedcpp.feature/epp.website.xml
- packages/org.eclipse.epp.package.java.feature/epp.website.xml
- packages/org.eclipse.epp.package.jee.feature/epp.website.xml
- packages/org.eclipse.epp.package.modeling.feature/epp.website.xml
- packages/org.eclipse.epp.package.php.feature/epp.website.xml
- packages/org.eclipse.epp.package.rcp.feature/epp.website.xml
- packages/org.eclipse.epp.package.scout.feature/epp.website.xml
- releng/org.eclipse.epp.config/parent/pom.xml
- releng/org.eclipse.epp.config/tools/upload-to-staging.sh
> Prepare repo for 2025-06 M3

- packages/org.eclipse.epp.package.committers.feature/epp.website.xml
- packages/org.eclipse.epp.package.cpp.feature/epp.website.xml
- packages/org.eclipse.epp.package.dsl.feature/epp.website.xml
- packages/org.eclipse.epp.package.embedcpp.feature/epp.website.xml
- packages/org.eclipse.epp.package.java.feature/epp.website.xml
- packages/org.eclipse.epp.package.jee.feature/epp.website.xml
- packages/org.eclipse.epp.package.modeling.feature/epp.website.xml
- packages/org.eclipse.epp.package.php.feature/epp.website.xml
- packages/org.eclipse.epp.package.rcp.feature/epp.website.xml
- packages/org.eclipse.epp.package.scout.feature/epp.website.xml
- releng/org.eclipse.epp.config/parent/pom.xml
- releng/org.eclipse.epp.config/tools/upload-to-staging.sh
> Prepare repo for 2025-06 RC2

- releng/org.eclipse.epp.config/.project
- releng/org.eclipse.epp.config/org.eclipse.epp.releng.updater/.classpath
- releng/org.eclipse.epp.config/org.eclipse.epp.releng.updater/.project
- releng/org.eclipse.epp.config/org.eclipse.epp.releng.updater/.settings/org.eclipse.core.resources.prefs
- releng/org.eclipse.epp.config/org.eclipse.epp.releng.updater/.settings/org.eclipse.jdt.core.prefs
- releng/org.eclipse.epp.config/org.eclipse.epp.releng.updater/src/org/eclipse/epp/releng/updater/Updater.java
- The goal is to automate all of the renaming steps in RELEASING.md.
> Provide a relatively simple Java class for updating versions

- RELEASING.md
- In particular break the very long lines into more
> Reformat RELEASING.md to make editing easier

- .gitignore
- releng/org.eclipse.epp.config/oomph/EPP.setup
> Create .settings/org.eclipse.core.resources.prefs in the clone root

- packages/org.eclipse.epp.package.committers.feature/epp.website.xml
- packages/org.eclipse.epp.package.cpp.feature/epp.website.xml
- packages/org.eclipse.epp.package.dsl.feature/epp.website.xml
- packages/org.eclipse.epp.package.embedcpp.feature/epp.website.xml
- packages/org.eclipse.epp.package.java.feature/epp.website.xml
- packages/org.eclipse.epp.package.jee.feature/epp.website.xml
- packages/org.eclipse.epp.package.modeling.feature/epp.website.xml
- packages/org.eclipse.epp.package.php.feature/epp.website.xml
- packages/org.eclipse.epp.package.rcp.feature/epp.website.xml
- packages/org.eclipse.epp.package.scout.feature/epp.website.xml
- releng/org.eclipse.epp.config/org.eclipse.epp.releng.updater/src/org/eclipse/epp/releng/updater/Updater.java
- releng/org.eclipse.epp.config/parent/pom.xml
https://github.com/eclipse-packaging/packages/issues/340
> Update to prepare for 2025-09 M2

- packages/org.eclipse.epp.package.committers.feature/epp.website.xml
- packages/org.eclipse.epp.package.cpp.feature/epp.website.xml
- packages/org.eclipse.epp.package.dsl.feature/epp.website.xml
- packages/org.eclipse.epp.package.embedcpp.feature/epp.website.xml
- packages/org.eclipse.epp.package.java.feature/epp.website.xml
- packages/org.eclipse.epp.package.jee.feature/epp.website.xml
- packages/org.eclipse.epp.package.modeling.feature/epp.website.xml
- packages/org.eclipse.epp.package.php.feature/epp.website.xml
- packages/org.eclipse.epp.package.rcp.feature/epp.website.xml
- packages/org.eclipse.epp.package.scout.feature/epp.website.xml
- releng/org.eclipse.epp.config/org.eclipse.epp.releng.updater/src/org/eclipse/epp/releng/updater/Updater.java
- releng/org.eclipse.epp.config/parent/pom.xml
Part of https://github.com/eclipse-packaging/packages/issues/347
> Back to staging with initial changes to prepare for RC1 builds.
